/**
 * Global Error Constants for Socius Platform
 * Centralized error codes for better client handling and debugging
 */

// Authentication & Authorization Errors
const AUTH_ERRORS = {
  NO_TOKEN: 'NO_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  VERIFICATION_REQUIRED: 'VERIFICATION_REQUIRED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  FORBIDDEN: 'FORBIDDEN',
  ADMIN_REQUIRED: 'ADMIN_REQUIRED',
  DEVELOPER_REQUIRED: 'DEVELOPER_REQUIRED'
}

// Presence Request Errors
const PRESENCE_ERRORS = {
  ACTIVE_REQUEST_EXISTS: 'ACTIVE_REQUEST_EXISTS',
  INVALID_COORDINATES: 'INVALID_COORDINATES',
  INVALID_SITUATION_TYPE: 'INVALID_SITUATION_TYPE',
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_CLOSED: 'REQUEST_CLOSED',
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  HELPER_BUSY: 'HELPER_BUSY',
  INVALID_STATUS: 'INVALID_STATUS',
  NO_HELPERS_FOUND: 'NO_HELPERS_FOUND',
  LOCATION_REQUIRED: 'LOCATION_REQUIRED',
  MAX_HELPERS_EXCEEDED: 'MAX_HELPERS_EXCEEDED',
  DESCRIPTION_TOO_LONG: 'DESCRIPTION_TOO_LONG',
  INVALID_CLOSURE_REASON: 'INVALID_CLOSURE_REASON'
}

// Help Request Errors
const HELP_REQUEST_ERRORS = {
  ACTIVE_REQUEST_EXISTS: 'HELP_ACTIVE_REQUEST_EXISTS',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  INVALID_DESCRIPTION: 'INVALID_DESCRIPTION',
  REQUEST_NOT_FOUND: 'HELP_REQUEST_NOT_FOUND',
  REQUEST_CLOSED: 'HELP_REQUEST_CLOSED',
  MATCH_NOT_FOUND: 'HELP_MATCH_NOT_FOUND',
  HELPER_BUSY: 'HELP_HELPER_BUSY',
  INVALID_STATUS: 'HELP_INVALID_STATUS',
  NO_HELPERS_FOUND: 'HELP_NO_HELPERS_FOUND',
  LOCATION_REQUIRED: 'HELP_LOCATION_REQUIRED',
  INVALID_TIME: 'HELP_INVALID_TIME',
  ITEM_RETURN_REQUIRED: 'HELP_ITEM_RETURN_REQUIRED'
}

// Location Service Errors
const LOCATION_ERRORS = {
  INVALID_COORDINATES: 'LOCATION_INVALID_COORDINATES',
  DATABASE_ERROR: 'LOCATION_DATABASE_ERROR',
  NO_HELPERS_FOUND: 'LOCATION_NO_HELPERS_FOUND',
  INVALID_RADIUS: 'LOCATION_INVALID_RADIUS',
  INVALID_LIMIT: 'LOCATION_INVALID_LIMIT',
  GEOCODING_FAILED: 'LOCATION_GEOCODING_FAILED',
  PERMISSION_DENIED: 'LOCATION_PERMISSION_DENIED'
}

// Validation Errors
const VALIDATION_ERRORS = {
  INVALID_INPUT: 'VALIDATION_INVALID_INPUT',
  REQUIRED_FIELD_MISSING: 'VALIDATION_REQUIRED_FIELD_MISSING',
  INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  INVALID_PHONE: 'VALIDATION_INVALID_PHONE',
  INVALID_PASSWORD: 'VALIDATION_INVALID_PASSWORD',
  INVALID_FILE_TYPE: 'VALIDATION_INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'VALIDATION_FILE_TOO_LARGE',
  INVALID_OTP: 'VALIDATION_INVALID_OTP',
  OTP_EXPIRED: 'VALIDATION_OTP_EXPIRED'
}

// Database Errors
const DATABASE_ERRORS = {
  CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
  DUPLICATE_KEY: 'DB_DUPLICATE_KEY',
  DOCUMENT_NOT_FOUND: 'DB_DOCUMENT_NOT_FOUND',
  VALIDATION_FAILED: 'DB_VALIDATION_FAILED',
  CAST_ERROR: 'DB_CAST_ERROR',
  TRANSACTION_FAILED: 'DB_TRANSACTION_FAILED'
}

// Notification Errors
const NOTIFICATION_ERRORS = {
  FCM_FAILED: 'NOTIF_FCM_FAILED',
  INVALID_TOKEN: 'NOTIF_INVALID_TOKEN',
  TOKEN_INVALIDATED: 'NOTIF_TOKEN_INVALIDATED',
  SEND_FAILED: 'NOTIF_SEND_FAILED',
  SOCKET_ERROR: 'NOTIF_SOCKET_ERROR'
}

// File Upload Errors
const FILE_ERRORS = {
  UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  INVALID_TYPE: 'FILE_INVALID_TYPE',
  TOO_LARGE: 'FILE_TOO_LARGE',
  CORRUPTED: 'FILE_CORRUPTED',
  PROCESSING_FAILED: 'FILE_PROCESSING_FAILED'
}

// Rate Limiting Errors
const RATE_LIMIT_ERRORS = {
  TOO_MANY_REQUESTS: 'RATE_LIMIT_TOO_MANY_REQUESTS',
  TEMPORARILY_BLOCKED: 'RATE_LIMIT_TEMPORARILY_BLOCKED',
  DAILY_LIMIT_EXCEEDED: 'RATE_LIMIT_DAILY_LIMIT_EXCEEDED',
  HOURLY_LIMIT_EXCEEDED: 'RATE_LIMIT_HOURLY_LIMIT_EXCEEDED'
}

// Business Logic Errors
const BUSINESS_ERRORS = {
  INSUFFICIENT_BALANCE: 'BUSINESS_INSUFFICIENT_BALANCE',
  SUBSCRIPTION_EXPIRED: 'BUSINESS_SUBSCRIPTION_EXPIRED',
  FEATURE_NOT_AVAILABLE: 'BUSINESS_FEATURE_NOT_AVAILABLE',
  INVALID_STATE_TRANSITION: 'BUSINESS_INVALID_STATE_TRANSITION',
  CONCURRENT_MODIFICATION: 'BUSINESS_CONCURRENT_MODIFICATION'
}

// External Service Errors
const EXTERNAL_SERVICE_ERRORS = {
  FIREBASE_ERROR: 'EXTERNAL_FIREBASE_ERROR',
  PAYMENT_FAILED: 'EXTERNAL_PAYMENT_FAILED',
  SMS_SERVICE_FAILED: 'EXTERNAL_SMS_SERVICE_FAILED',
  EMAIL_SERVICE_FAILED: 'EXTERNAL_EMAIL_SERVICE_FAILED',
  GEOCODING_SERVICE_FAILED: 'EXTERNAL_GEOCODING_SERVICE_FAILED'
}

// Error Message Templates
const ERROR_MESSAGES = {
  // Auth Messages
  [AUTH_ERRORS.NO_TOKEN]: 'Authentication token is required',
  [AUTH_ERRORS.INVALID_TOKEN]: 'Invalid authentication token',
  [AUTH_ERRORS.TOKEN_EXPIRED]: 'Your session has expired. Please login again',
  [AUTH_ERRORS.USER_NOT_FOUND]: 'User not found. Please login again',
  [AUTH_ERRORS.ACCOUNT_SUSPENDED]: 'Your account has been suspended. Please contact support',
  [AUTH_ERRORS.ACCOUNT_PENDING]: 'Your account is pending review or limited',
  [AUTH_ERRORS.VERIFICATION_REQUIRED]: 'Identity verification required for this action',
  [AUTH_ERRORS.ACCOUNT_INACTIVE]: 'Your account is not active. Please contact support',

  // Presence Messages
  [PRESENCE_ERRORS.ACTIVE_REQUEST_EXISTS]: 'You already have an active presence request',
  [PRESENCE_ERRORS.INVALID_COORDINATES]: 'Invalid coordinates provided',
  [PRESENCE_ERRORS.INVALID_SITUATION_TYPE]: 'Invalid situation type',
  [PRESENCE_ERRORS.REQUEST_NOT_FOUND]: 'Presence request not found',
  [PRESENCE_ERRORS.REQUEST_CLOSED]: 'Presence request is already closed',
  [PRESENCE_ERRORS.MATCH_NOT_FOUND]: 'No active presence match found',
  [PRESENCE_ERRORS.HELPER_BUSY]: 'You have an active request. Please close it first',
  [PRESENCE_ERRORS.INVALID_STATUS]: 'Invalid status provided',
  [PRESENCE_ERRORS.NO_HELPERS_FOUND]: 'No helpers found in your area',
  [PRESENCE_ERRORS.LOCATION_REQUIRED]: 'Location is required',
  [PRESENCE_ERRORS.MAX_HELPERS_EXCEEDED]: 'Maximum helpers limit exceeded',
  [PRESENCE_ERRORS.DESCRIPTION_TOO_LONG]: 'Description is too long',
  [PRESENCE_ERRORS.INVALID_CLOSURE_REASON]: 'Invalid closure reason',

  // Location Messages
  [LOCATION_ERRORS.INVALID_COORDINATES]: 'Invalid coordinates. Latitude must be between -90 and 90, longitude between -180 and 180',
  [LOCATION_ERRORS.DATABASE_ERROR]: 'Database error occurred while finding location',
  [LOCATION_ERRORS.NO_HELPERS_FOUND]: 'No helpers found in the specified area',
  [LOCATION_ERRORS.INVALID_RADIUS]: 'Invalid search radius',
  [LOCATION_ERRORS.INVALID_LIMIT]: 'Invalid result limit',
  [LOCATION_ERRORS.GEOCODING_FAILED]: 'Failed to geocode location',
  [LOCATION_ERRORS.PERMISSION_DENIED]: 'Location permission denied',

  // Validation Messages
  [VALIDATION_ERRORS.INVALID_INPUT]: 'Invalid input provided',
  [VALIDATION_ERRORS.REQUIRED_FIELD_MISSING]: 'Required field is missing',
  [VALIDATION_ERRORS.INVALID_EMAIL]: 'Invalid email address',
  [VALIDATION_ERRORS.INVALID_PHONE]: 'Invalid phone number',
  [VALIDATION_ERRORS.INVALID_PASSWORD]: 'Invalid password',
  [VALIDATION_ERRORS.INVALID_FILE_TYPE]: 'Invalid file type',
  [VALIDATION_ERRORS.FILE_TOO_LARGE]: 'File size too large',
  [VALIDATION_ERRORS.INVALID_OTP]: 'Invalid OTP',
  [VALIDATION_ERRORS.OTP_EXPIRED]: 'OTP has expired',

  // Rate Limit Messages
  [RATE_LIMIT_ERRORS.TOO_MANY_REQUESTS]: 'Too many requests. Please try again later',
  [RATE_LIMIT_ERRORS.TEMPORARILY_BLOCKED]: 'You are temporarily blocked. Please try again later',
  [RATE_LIMIT_ERRORS.DAILY_LIMIT_EXCEEDED]: 'Daily request limit exceeded',
  [RATE_LIMIT_ERRORS.HOURLY_LIMIT_EXCEEDED]: 'Hourly request limit exceeded'
}

// HTTP Status Code Mapping
const HTTP_STATUS_CODES = {
  // Success
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,

  // Client Errors
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,

  // Server Errors
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504
}

// Error Status Code Mapping
const ERROR_STATUS_MAPPING = {
  // Auth errors
  [AUTH_ERRORS.NO_TOKEN]: HTTP_STATUS_CODES.UNAUTHORIZED,
  [AUTH_ERRORS.INVALID_TOKEN]: HTTP_STATUS_CODES.UNAUTHORIZED,
  [AUTH_ERRORS.TOKEN_EXPIRED]: HTTP_STATUS_CODES.UNAUTHORIZED,
  [AUTH_ERRORS.USER_NOT_FOUND]: HTTP_STATUS_CODES.UNAUTHORIZED,
  [AUTH_ERRORS.ACCOUNT_SUSPENDED]: HTTP_STATUS_CODES.FORBIDDEN,
  [AUTH_ERRORS.ACCOUNT_PENDING]: HTTP_STATUS_CODES.FORBIDDEN,
  [AUTH_ERRORS.VERIFICATION_REQUIRED]: HTTP_STATUS_CODES.FORBIDDEN,
  [AUTH_ERRORS.ACCOUNT_INACTIVE]: HTTP_STATUS_CODES.UNAUTHORIZED,
  [AUTH_ERRORS.FORBIDDEN]: HTTP_STATUS_CODES.FORBIDDEN,

  // Presence errors
  [PRESENCE_ERRORS.ACTIVE_REQUEST_EXISTS]: HTTP_STATUS_CODES.CONFLICT,
  [PRESENCE_ERRORS.INVALID_COORDINATES]: HTTP_STATUS_CODES.BAD_REQUEST,
  [PRESENCE_ERRORS.INVALID_SITUATION_TYPE]: HTTP_STATUS_CODES.BAD_REQUEST,
  [PRESENCE_ERRORS.REQUEST_NOT_FOUND]: HTTP_STATUS_CODES.NOT_FOUND,
  [PRESENCE_ERRORS.REQUEST_CLOSED]: HTTP_STATUS_CODES.CONFLICT,
  [PRESENCE_ERRORS.MATCH_NOT_FOUND]: HTTP_STATUS_CODES.NOT_FOUND,
  [PRESENCE_ERRORS.HELPER_BUSY]: HTTP_STATUS_CODES.CONFLICT,
  [PRESENCE_ERRORS.INVALID_STATUS]: HTTP_STATUS_CODES.BAD_REQUEST,
  [PRESENCE_ERRORS.LOCATION_REQUIRED]: HTTP_STATUS_CODES.BAD_REQUEST,
  [PRESENCE_ERRORS.MAX_HELPERS_EXCEEDED]: HTTP_STATUS_CODES.BAD_REQUEST,
  [PRESENCE_ERRORS.DESCRIPTION_TOO_LONG]: HTTP_STATUS_CODES.BAD_REQUEST,
  [PRESENCE_ERRORS.INVALID_CLOSURE_REASON]: HTTP_STATUS_CODES.BAD_REQUEST,

  // Location errors
  [LOCATION_ERRORS.INVALID_COORDINATES]: HTTP_STATUS_CODES.BAD_REQUEST,
  [LOCATION_ERRORS.DATABASE_ERROR]: HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR,
  [LOCATION_ERRORS.INVALID_RADIUS]: HTTP_STATUS_CODES.BAD_REQUEST,
  [LOCATION_ERRORS.INVALID_LIMIT]: HTTP_STATUS_CODES.BAD_REQUEST,

  // Validation errors
  [VALIDATION_ERRORS.INVALID_INPUT]: HTTP_STATUS_CODES.BAD_REQUEST,
  [VALIDATION_ERRORS.REQUIRED_FIELD_MISSING]: HTTP_STATUS_CODES.BAD_REQUEST,
  [VALIDATION_ERRORS.INVALID_EMAIL]: HTTP_STATUS_CODES.BAD_REQUEST,
  [VALIDATION_ERRORS.INVALID_PHONE]: HTTP_STATUS_CODES.BAD_REQUEST,
  [VALIDATION_ERRORS.INVALID_PASSWORD]: HTTP_STATUS_CODES.BAD_REQUEST,
  [VALIDATION_ERRORS.INVALID_FILE_TYPE]: HTTP_STATUS_CODES.BAD_REQUEST,
  [VALIDATION_ERRORS.FILE_TOO_LARGE]: HTTP_STATUS_CODES.BAD_REQUEST,
  [VALIDATION_ERRORS.INVALID_OTP]: HTTP_STATUS_CODES.BAD_REQUEST,
  [VALIDATION_ERRORS.OTP_EXPIRED]: HTTP_STATUS_CODES.BAD_REQUEST,

  // Rate limit errors
  [RATE_LIMIT_ERRORS.TOO_MANY_REQUESTS]: HTTP_STATUS_CODES.TOO_MANY_REQUESTS,
  [RATE_LIMIT_ERRORS.TEMPORARILY_BLOCKED]: HTTP_STATUS_CODES.TOO_MANY_REQUESTS,
  [RATE_LIMIT_ERRORS.DAILY_LIMIT_EXCEEDED]: HTTP_STATUS_CODES.TOO_MANY_REQUESTS,
  [RATE_LIMIT_ERRORS.HOURLY_LIMIT_EXCEEDED]: HTTP_STATUS_CODES.TOO_MANY_REQUESTS
}

module.exports = {
  AUTH_ERRORS,
  PRESENCE_ERRORS,
  HELP_REQUEST_ERRORS,
  LOCATION_ERRORS,
  VALIDATION_ERRORS,
  DATABASE_ERRORS,
  NOTIFICATION_ERRORS,
  FILE_ERRORS,
  RATE_LIMIT_ERRORS,
  BUSINESS_ERRORS,
  EXTERNAL_SERVICE_ERRORS,
  ERROR_MESSAGES,
  HTTP_STATUS_CODES,
  ERROR_STATUS_MAPPING
}
