export const countries = [
  { code: 'IN', name: 'India', dial: '+91', flag: '🇮🇳', maxLength: 10 },
  { code: 'NP', name: 'Nepal', dial: '+977', flag: '🇳🇵', maxLength: 10 },
  { code: 'PK', name: 'Pakistan', dial: '+92', flag: '🇵🇰', maxLength: 10 },
  { code: 'QA', name: 'Qatar', dial: '+974', flag: '🇶🇦', maxLength: 8 },
  { code: 'SA', name: 'Saudi Arabia', dial: '+966', flag: '🇸🇦', maxLength: 9 },
  { code: 'AF', name: 'Afghanistan', dial: '+93', flag: '🇦🇫', maxLength: 9 },
  { code: 'AL', name: 'Albania', dial: '+355', flag: '🇦🇱', maxLength: 9 },
  { code: 'DZ', name: 'Algeria', dial: '+213', flag: '🇩🇿', maxLength: 9 },
  { code: 'AS', name: 'American Samoa', dial: '+1684', flag: '🇦🇸', maxLength: 7 },
  { code: 'AD', name: 'Andorra', dial: '+376', flag: '🇦🇩', maxLength: 6 },
  { code: 'AO', name: 'Angola', dial: '+244', flag: '🇦🇴', maxLength: 9 },
  { code: 'AI', name: 'Anguilla', dial: '+1264', flag: '🇦🇮', maxLength: 7 },
  { code: 'AG', name: 'Antigua and Barbuda', dial: '+1268', flag: '🇦🇬', maxLength: 7 },
  { code: 'AR', name: 'Argentina', dial: '+54', flag: '🇦🇷', maxLength: 10 },
  { code: 'AM', name: 'Armenia', dial: '+374', flag: '🇦🇲', maxLength: 8 },
  { code: 'AW', name: 'Aruba', dial: '+297', flag: '🇦🇼', maxLength: 7 },
  { code: 'AU', name: 'Australia', dial: '+61', flag: '🇦🇺', maxLength: 9 },
  { code: 'AT', name: 'Austria', dial: '+43', flag: '🇦🇹', maxLength: 10 },
  { code: 'AZ', name: 'Azerbaijan', dial: '+994', flag: '🇦🇿', maxLength: 9 },
  { code: 'BS', name: 'Bahamas', dial: '+1242', flag: '🇧🇸', maxLength: 7 },
  { code: 'BH', name: 'Bahrain', dial: '+973', flag: '🇧🇭', maxLength: 8 },
  { code: 'BD', name: 'Bangladesh', dial: '+880', flag: '🇧🇩', maxLength: 11 },
  { code: 'BB', name: 'Barbados', dial: '+1246', flag: '🇧🇧', maxLength: 7 },
  { code: 'BY', name: 'Belarus', dial: '+375', flag: '🇧🇾', maxLength: 9 },
  { code: 'BE', name: 'Belgium', dial: '+32', flag: '🇧🇪', maxLength: 9 },
  { code: 'BZ', name: 'Belize', dial: '+501', flag: '🇧🇿', maxLength: 7 },
  { code: 'BJ', name: 'Benin', dial: '+229', flag: '🇧🇯', maxLength: 8 },
  { code: 'BM', name: 'Bermuda', dial: '+1441', flag: '🇧🇲', maxLength: 7 },
  { code: 'BT', name: 'Bhutan', dial: '+975', flag: '🇧🇹', maxLength: 8 },
  { code: 'BO', name: 'Bolivia', dial: '+591', flag: '🇧🇴', maxLength: 8 },
  { code: 'BA', name: 'Bosnia and Herzegovina', dial: '+387', flag: '🇧🇦', maxLength: 8 },
  { code: 'BW', name: 'Botswana', dial: '+267', flag: '🇧🇼', maxLength: 8 },
  { code: 'BR', name: 'Brazil', dial: '+55', flag: '🇧🇷', maxLength: 11 },
  { code: 'IO', name: 'British Indian Ocean Territory', dial: '+246', flag: '🇮🇴', maxLength: 7 },
  { code: 'VG', name: 'British Virgin Islands', dial: '+1284', flag: '🇻🇬', maxLength: 7 },
  { code: 'BN', name: 'Brunei', dial: '+673', flag: '🇧🇳', maxLength: 7 },
  { code: 'BG', name: 'Bulgaria', dial: '+359', flag: '🇧🇬', maxLength: 9 },
  { code: 'BF', name: 'Burkina Faso', dial: '+226', flag: '🇧🇫', maxLength: 8 },
  { code: 'BI', name: 'Burundi', dial: '+257', flag: '🇧🇮', maxLength: 8 },
  { code: 'KH', name: 'Cambodia', dial: '+855', flag: '🇰🇭', maxLength: 9 },
  { code: 'CM', name: 'Cameroon', dial: '+237', flag: '🇨🇲', maxLength: 9 },
  { code: 'CA', name: 'Canada', dial: '+1', flag: '🇨🇦', maxLength: 10 },
  { code: 'CV', name: 'Cape Verde', dial: '+238', flag: '🇨🇻', maxLength: 7 },
  { code: 'KY', name: 'Cayman Islands', dial: '+1345', flag: '🇰🇾', maxLength: 7 },
  { code: 'CF', name: 'Central African Republic', dial: '+236', flag: '🇨🇫', maxLength: 8 },
  { code: 'TD', name: 'Chad', dial: '+235', flag: '🇹🇩', maxLength: 8 },
  { code: 'CL', name: 'Chile', dial: '+56', flag: '🇨🇱', maxLength: 9 },
  { code: 'CN', name: 'China', dial: '+86', flag: '🇨🇳', maxLength: 11 },
  { code: 'CX', name: 'Christmas Island', dial: '+61', flag: '🇨🇽', maxLength: 9 },
  { code: 'CC', name: 'Cocos (Keeling) Islands', dial: '+61', flag: '🇨🇨', maxLength: 9 },
  { code: 'CO', name: 'Colombia', dial: '+57', flag: '🇨🇴', maxLength: 10 },
  { code: 'KM', name: 'Comoros', dial: '+269', flag: '🇰🇲', maxLength: 7 },
  { code: 'CG', name: 'Congo', dial: '+242', flag: '🇨🇬', maxLength: 9 },
  { code: 'CD', name: 'Congo, Democratic Republic of the', dial: '+243', flag: '🇨🇩', maxLength: 9 },
  { code: 'CK', name: 'Cook Islands', dial: '+682', flag: '🇨🇰', maxLength: 5 },
  { code: 'CR', name: 'Costa Rica', dial: '+506', flag: '🇨🇷', maxLength: 8 },
  { code: 'CI', name: 'Côte d\'Ivoire', dial: '+225', flag: '🇨🇮', maxLength: 10 },
  { code: 'HR', name: 'Croatia', dial: '+385', flag: '🇭🇷', maxLength: 9 },
  { code: 'CU', name: 'Cuba', dial: '+53', flag: '🇨🇺', maxLength: 8 },
  { code: 'CY', name: 'Cyprus', dial: '+357', flag: '🇨🇾', maxLength: 8 },
  { code: 'CZ', name: 'Czech Republic', dial: '+420', flag: '🇨🇿', maxLength: 9 },
  { code: 'DK', name: 'Denmark', dial: '+45', flag: '🇩🇰', maxLength: 8 },
  { code: 'DJ', name: 'Djibouti', dial: '+253', flag: '🇩🇯', maxLength: 8 },
  { code: 'DM', name: 'Dominica', dial: '+1767', flag: '🇩🇲', maxLength: 7 },
  { code: 'DO', name: 'Dominican Republic', dial: '+1', flag: '🇩🇴', maxLength: 10 },
  { code: 'EC', name: 'Ecuador', dial: '+593', flag: '🇪🇨', maxLength: 9 },
  { code: 'EG', name: 'Egypt', dial: '+20', flag: '🇪🇬', maxLength: 10 },
  { code: 'SV', name: 'El Salvador', dial: '+503', flag: '🇸🇻', maxLength: 8 },
  { code: 'GQ', name: 'Equatorial Guinea', dial: '+240', flag: '🇬🇶', maxLength: 9 },
  { code: 'ER', name: 'Eritrea', dial: '+291', flag: '🇪🇷', maxLength: 7 },
  { code: 'EE', name: 'Estonia', dial: '+372', flag: '🇪🇪', maxLength: 8 },
  { code: 'ET', name: 'Ethiopia', dial: '+251', flag: '🇪🇹', maxLength: 9 },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', dial: '+500', flag: '🇫🇰', maxLength: 5 },
  { code: 'FO', name: 'Faroe Islands', dial: '+298', flag: '🇫🇴', maxLength: 6 },
  { code: 'FJ', name: 'Fiji', dial: '+679', flag: '🇫🇯', maxLength: 7 },
  { code: 'FI', name: 'Finland', dial: '+358', flag: '🇫🇮', maxLength: 10 },
  { code: 'FR', name: 'France', dial: '+33', flag: '🇫🇷', maxLength: 9 },
  { code: 'GF', name: 'French Guiana', dial: '+594', flag: '🇬🇫', maxLength: 9 },
  { code: 'PF', name: 'French Polynesia', dial: '+689', flag: '🇵🇫', maxLength: 6 },
  { code: 'GA', name: 'Gabon', dial: '+241', flag: '🇬🇦', maxLength: 7 },
  { code: 'GM', name: 'Gambia', dial: '+220', flag: '🇬🇲', maxLength: 7 },
  { code: 'GE', name: 'Georgia', dial: '+995', flag: '🇬🇪', maxLength: 9 },
  { code: 'DE', name: 'Germany', dial: '+49', flag: '🇩🇪', maxLength: 11 },
  { code: 'GH', name: 'Ghana', dial: '+233', flag: '🇬🇭', maxLength: 9 },
  { code: 'GI', name: 'Gibraltar', dial: '+350', flag: '🇬🇮', maxLength: 8 },
  { code: 'GR', name: 'Greece', dial: '+30', flag: '🇬🇷', maxLength: 10 },
  { code: 'GL', name: 'Greenland', dial: '+299', flag: '🇬🇱', maxLength: 6 },
  { code: 'GD', name: 'Grenada', dial: '+1473', flag: '🇬🇩', maxLength: 7 },
  { code: 'GP', name: 'Guadeloupe', dial: '+590', flag: '🇬🇵', maxLength: 9 },
  { code: 'GU', name: 'Guam', dial: '+1671', flag: '🇬🇺', maxLength: 7 },
  { code: 'GT', name: 'Guatemala', dial: '+502', flag: '🇬🇹', maxLength: 8 },
  { code: 'GG', name: 'Guernsey', dial: '+44', flag: '🇬🇬', maxLength: 10 },
  { code: 'GN', name: 'Guinea', dial: '+224', flag: '🇬🇳', maxLength: 9 },
  { code: 'GW', name: 'Guinea-Bissau', dial: '+245', flag: '🇬🇼', maxLength: 7 },
  { code: 'GY', name: 'Guyana', dial: '+592', flag: '🇬🇾', maxLength: 7 },
  { code: 'HT', name: 'Haiti', dial: '+509', flag: '🇭🇹', maxLength: 8 },
  { code: 'VA', name: 'Holy See (Vatican City State)', dial: '+379', flag: '🇻🇦', maxLength: 10 },
  { code: 'HN', name: 'Honduras', dial: '+504', flag: '🇭🇳', maxLength: 8 },
  { code: 'HK', name: 'Hong Kong', dial: '+852', flag: '🇭🇰', maxLength: 8 },
  { code: 'HU', name: 'Hungary', dial: '+36', flag: '🇭🇺', maxLength: 9 },
  { code: 'IS', name: 'Iceland', dial: '+354', flag: '🇮🇸', maxLength: 7 },
  { code: 'ID', name: 'Indonesia', dial: '+62', flag: '🇮🇩', maxLength: 11 },
  { code: 'IR', name: 'Iran', dial: '+98', flag: '🇮🇷', maxLength: 10 },
  { code: 'IQ', name: 'Iraq', dial: '+964', flag: '🇮🇶', maxLength: 10 },
  { code: 'IE', name: 'Ireland', dial: '+353', flag: '🇮🇪', maxLength: 9 },
  { code: 'IM', name: 'Isle of Man', dial: '+44', flag: '🇮🇲', maxLength: 10 },
  { code: 'IL', name: 'Israel', dial: '+972', flag: '🇮🇱', maxLength: 9 },
  { code: 'IT', name: 'Italy', dial: '+39', flag: '🇮🇹', maxLength: 10 },
  { code: 'JM', name: 'Jamaica', dial: '+1876', flag: '🇯🇲', maxLength: 7 },
  { code: 'JP', name: 'Japan', dial: '+81', flag: '🇯🇵', maxLength: 10 },
  { code: 'JE', name: 'Jersey', dial: '+44', flag: '🇯🇪', maxLength: 10 },
  { code: 'JO', name: 'Jordan', dial: '+962', flag: '🇯🇴', maxLength: 9 },
  { code: 'KZ', name: 'Kazakhstan', dial: '+7', flag: '🇰🇿', maxLength: 10 },
  { code: 'KE', name: 'Kenya', dial: '+254', flag: '🇰🇪', maxLength: 9 },
  { code: 'KI', name: 'Kiribati', dial: '+686', flag: '🇰🇮', maxLength: 5 },
  { code: 'KP', name: 'Korea, Democratic People\'s Republic of', dial: '+850', flag: '🇰🇵', maxLength: 10 },
  { code: 'KR', name: 'Korea, Republic of', dial: '+82', flag: '🇰🇷', maxLength: 10 },
  { code: 'KW', name: 'Kuwait', dial: '+965', flag: '🇰🇼', maxLength: 8 },
  { code: 'KG', name: 'Kyrgyzstan', dial: '+996', flag: '🇰🇬', maxLength: 9 },
  { code: 'LA', name: 'Lao People\'s Democratic Republic', dial: '+856', flag: '🇱🇦', maxLength: 10 },
  { code: 'LV', name: 'Latvia', dial: '+371', flag: '🇱🇻', maxLength: 8 },
  { code: 'LB', name: 'Lebanon', dial: '+961', flag: '🇱🇧', maxLength: 8 },
  { code: 'LS', name: 'Lesotho', dial: '+266', flag: '🇱🇸', maxLength: 8 },
  { code: 'LR', name: 'Liberia', dial: '+231', flag: '🇱🇷', maxLength: 8 },
  { code: 'LY', name: 'Libya', dial: '+218', flag: '🇱🇾', maxLength: 9 },
  { code: 'LI', name: 'Liechtenstein', dial: '+423', flag: '🇱🇮', maxLength: 7 },
  { code: 'LT', name: 'Lithuania', dial: '+370', flag: '🇱🇹', maxLength: 8 },
  { code: 'LU', name: 'Luxembourg', dial: '+352', flag: '🇱🇺', maxLength: 9 },
  { code: 'MO', name: 'Macao', dial: '+853', flag: '🇲🇴', maxLength: 8 },
  { code: 'MK', name: 'Macedonia', dial: '+389', flag: '🇲🇰', maxLength: 8 },
  { code: 'MG', name: 'Madagascar', dial: '+261', flag: '🇲🇬', maxLength: 9 },
  { code: 'MW', name: 'Malawi', dial: '+265', flag: '🇲🇼', maxLength: 9 },
  { code: 'MY', name: 'Malaysia', dial: '+60', flag: '🇲🇾', maxLength: 9 },
  { code: 'MV', name: 'Maldives', dial: '+960', flag: '🇲🇻', maxLength: 7 },
  { code: 'ML', name: 'Mali', dial: '+223', flag: '🇲🇱', maxLength: 8 },
  { code: 'MT', name: 'Malta', dial: '+356', flag: '🇲🇹', maxLength: 8 },
  { code: 'MH', name: 'Marshall Islands', dial: '+692', flag: '🇲🇭', maxLength: 7 },
  { code: 'MQ', name: 'Martinique', dial: '+596', flag: '🇲🇶', maxLength: 9 },
  { code: 'MR', name: 'Mauritania', dial: '+222', flag: '🇲🇷', maxLength: 8 },
  { code: 'MU', name: 'Mauritius', dial: '+230', flag: '🇲🇺', maxLength: 7 },
  { code: 'YT', name: 'Mayotte', dial: '+262', flag: '🇾🇹', maxLength: 9 },
  { code: 'MX', name: 'Mexico', dial: '+52', flag: '🇲🇽', maxLength: 10 },
  { code: 'FM', name: 'Micronesia, Federated States of', dial: '+691', flag: '🇫🇲', maxLength: 7 },
  { code: 'MD', name: 'Moldova', dial: '+373', flag: '🇲🇩', maxLength: 8 },
  { code: 'MC', name: 'Monaco', dial: '+377', flag: '🇲🇨', maxLength: 8 },
  { code: 'MN', name: 'Mongolia', dial: '+976', flag: '🇲🇳', maxLength: 8 },
  { code: 'ME', name: 'Montenegro', dial: '+382', flag: '🇲🇪', maxLength: 8 },
  { code: 'MS', name: 'Montserrat', dial: '+1664', flag: '🇲🇸', maxLength: 7 },
  { code: 'MA', name: 'Morocco', dial: '+212', flag: '🇲🇦', maxLength: 9 },
  { code: 'MZ', name: 'Mozambique', dial: '+258', flag: '🇲🇿', maxLength: 9 },
  { code: 'MM', name: 'Myanmar', dial: '+95', flag: '🇲🇲', maxLength: 9 },
  { code: 'NA', name: 'Namibia', dial: '+264', flag: '🇳🇦', maxLength: 9 },
  { code: 'NR', name: 'Nauru', dial: '+674', flag: '🇳🇷', maxLength: 7 },
  { code: 'NL', name: 'Netherlands', dial: '+31', flag: '🇳🇱', maxLength: 9 },
  { code: 'NC', name: 'New Caledonia', dial: '+687', flag: '🇳🇨', maxLength: 6 },
  { code: 'NZ', name: 'New Zealand', dial: '+64', flag: '🇳🇿', maxLength: 9 },
  { code: 'NI', name: 'Nicaragua', dial: '+505', flag: '🇳🇮', maxLength: 8 },
  { code: 'NE', name: 'Niger', dial: '+227', flag: '🇳🇪', maxLength: 8 },
  { code: 'NG', name: 'Nigeria', dial: '+234', flag: '🇳🇬', maxLength: 10 },
  { code: 'NU', name: 'Niue', dial: '+683', flag: '🇳🇺', maxLength: 4 },
  { code: 'NF', name: 'Norfolk Island', dial: '+672', flag: '🇳🇫', maxLength: 6 },
  { code: 'MP', name: 'Northern Mariana Islands', dial: '+1670', flag: '🇲🇵', maxLength: 7 },
  { code: 'NO', name: 'Norway', dial: '+47', flag: '🇳🇴', maxLength: 8 },
  { code: 'OM', name: 'Oman', dial: '+968', flag: '🇴🇲', maxLength: 8 },
  { code: 'PW', name: 'Palau', dial: '+680', flag: '🇵🇼', maxLength: 7 },
  { code: 'PS', name: 'Palestinian Territory, Occupied', dial: '+970', flag: '🇵🇸', maxLength: 9 },
  { code: 'PA', name: 'Panama', dial: '+507', flag: '🇵🇦', maxLength: 8 },
  { code: 'PG', name: 'Papua New Guinea', dial: '+675', flag: '🇵🇬', maxLength: 8 },
  { code: 'PY', name: 'Paraguay', dial: '+595', flag: '🇵🇾', maxLength: 9 },
  { code: 'PE', name: 'Peru', dial: '+51', flag: '🇵🇪', maxLength: 9 },
  { code: 'PH', name: 'Philippines', dial: '+63', flag: '🇵🇭', maxLength: 10 },
  { code: 'PN', name: 'Pitcairn', dial: '+64', flag: '🇵🇳', maxLength: 2 },
  { code: 'PL', name: 'Poland', dial: '+48', flag: '🇵🇱', maxLength: 9 },
  { code: 'PT', name: 'Portugal', dial: '+351', flag: '🇵🇹', maxLength: 9 },
  { code: 'PR', name: 'Puerto Rico', dial: '+1787', flag: '🇵🇷', maxLength: 7 },
  { code: 'RE', name: 'Réunion', dial: '+262', flag: '🇷🇪', maxLength: 9 },
  { code: 'RO', name: 'Romania', dial: '+40', flag: '🇷🇴', maxLength: 9 },
  { code: 'RU', name: 'Russia', dial: '+7', flag: '🇷🇺', maxLength: 10 },
  { code: 'RW', name: 'Rwanda', dial: '+250', flag: '🇷🇼', maxLength: 9 },
  { code: 'BL', name: 'Saint Barthélemy', dial: '+590', flag: '🇧🇱', maxLength: 9 },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', dial: '+290', flag: '🇸🇭', maxLength: 4 },
  { code: 'KN', name: 'Saint Kitts and Nevis', dial: '+1869', flag: '🇰🇳', maxLength: 7 },
  { code: 'LC', name: 'Saint Lucia', dial: '+1758', flag: '🇱🇨', maxLength: 7 },
  { code: 'MF', name: 'Saint Martin (French part)', dial: '+590', flag: '🇲🇫', maxLength: 9 },
  { code: 'PM', name: 'Saint Pierre and Miquelon', dial: '+508', flag: '🇵🇲', maxLength: 6 },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', dial: '+1784', flag: '🇻🇨', maxLength: 7 },
  { code: 'WS', name: 'Samoa', dial: '+685', flag: '🇼🇸', maxLength: 5 },
  { code: 'SM', name: 'San Marino', dial: '+378', flag: '🇸🇲', maxLength: 10 },
  { code: 'ST', name: 'Sao Tome and Principe', dial: '+239', flag: '🇸🇹', maxLength: 7 },
  { code: 'SN', name: 'Senegal', dial: '+221', flag: '🇸🇳', maxLength: 9 },
  { code: 'RS', name: 'Serbia', dial: '+381', flag: '🇷🇸', maxLength: 9 },
  { code: 'SC', name: 'Seychelles', dial: '+248', flag: '🇸🇨', maxLength: 7 },
  { code: 'SL', name: 'Sierra Leone', dial: '+232', flag: '🇸🇱', maxLength: 8 },
  { code: 'SG', name: 'Singapore', dial: '+65', flag: '🇸🇬', maxLength: 8 },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', dial: '+1721', flag: '🇸🇽', maxLength: 7 },
  { code: 'SK', name: 'Slovakia', dial: '+421', flag: '🇸🇰', maxLength: 9 },
  { code: 'SI', name: 'Slovenia', dial: '+386', flag: '🇸🇮', maxLength: 8 },
  { code: 'SB', name: 'Solomon Islands', dial: '+677', flag: '🇸🇧', maxLength: 7 },
  { code: 'SO', name: 'Somalia', dial: '+252', flag: '🇸🇴', maxLength: 9 },
  { code: 'ZA', name: 'South Africa', dial: '+27', flag: '🇿🇦', maxLength: 9 },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', dial: '+500', flag: '🇬🇸', maxLength: 5 },
  { code: 'SS', name: 'South Sudan', dial: '+211', flag: '🇸🇸', maxLength: 9 },
  { code: 'ES', name: 'Spain', dial: '+34', flag: '🇪🇸', maxLength: 9 },
  { code: 'LK', name: 'Sri Lanka', dial: '+94', flag: '🇱🇰', maxLength: 10 },
  { code: 'SD', name: 'Sudan', dial: '+249', flag: '🇸🇩', maxLength: 9 },
  { code: 'SR', name: 'Suriname', dial: '+597', flag: '🇸🇷', maxLength: 7 },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', dial: '+47', flag: '🇸🇯', maxLength: 8 },
  { code: 'SZ', name: 'Swaziland', dial: '+268', flag: '🇸🇿', maxLength: 8 },
  { code: 'SE', name: 'Sweden', dial: '+46', flag: '🇸🇪', maxLength: 9 },
  { code: 'CH', name: 'Switzerland', dial: '+41', flag: '🇨🇭', maxLength: 9 },
  { code: 'SY', name: 'Syrian Arab Republic', dial: '+963', flag: '🇸🇾', maxLength: 9 },
  { code: 'TW', name: 'Taiwan', dial: '+886', flag: '🇹🇼', maxLength: 9 },
  { code: 'TJ', name: 'Tajikistan', dial: '+992', flag: '🇹🇯', maxLength: 9 },
  { code: 'TZ', name: 'Tanzania', dial: '+255', flag: '🇹🇿', maxLength: 9 },
  { code: 'TH', name: 'Thailand', dial: '+66', flag: '🇹🇭', maxLength: 9 },
  { code: 'TL', name: 'Timor-Leste', dial: '+670', flag: '🇹🇱', maxLength: 7 },
  { code: 'TG', name: 'Togo', dial: '+228', flag: '🇹🇬', maxLength: 8 },
  { code: 'TK', name: 'Tokelau', dial: '+690', flag: '🇹🇰', maxLength: 4 },
  { code: 'TO', name: 'Tonga', dial: '+676', flag: '🇹🇴', maxLength: 7 },
  { code: 'TT', name: 'Trinidad and Tobago', dial: '+1868', flag: '🇹🇹', maxLength: 7 },
  { code: 'TN', name: 'Tunisia', dial: '+216', flag: '🇹🇳', maxLength: 8 },
  { code: 'TR', name: 'Turkey', dial: '+90', flag: '🇹🇷', maxLength: 10 },
  { code: 'TM', name: 'Turkmenistan', dial: '+993', flag: '🇹🇲', maxLength: 8 },
  { code: 'TC', name: 'Turks and Caicos Islands', dial: '+1649', flag: '🇹🇨', maxLength: 7 },
  { code: 'TV', name: 'Tuvalu', dial: '+688', flag: '🇹🇻', maxLength: 5 },
  { code: 'UG', name: 'Uganda', dial: '+256', flag: '🇺🇬', maxLength: 9 },
  { code: 'UA', name: 'Ukraine', dial: '+380', flag: '🇺🇦', maxLength: 9 },
  { code: 'AE', name: 'United Arab Emirates', dial: '+971', flag: '🇦🇪', maxLength: 9 },
  { code: 'GB', name: 'United Kingdom', dial: '+44', flag: '🇬🇧', maxLength: 10 },
  { code: 'US', name: 'United States', dial: '+1', flag: '🇺🇸', maxLength: 10 },
  { code: 'UY', name: 'Uruguay', dial: '+598', flag: '🇺🇾', maxLength: 8 },
  { code: 'UZ', name: 'Uzbekistan', dial: '+998', flag: '🇺🇿', maxLength: 9 },
  { code: 'VU', name: 'Vanuatu', dial: '+678', flag: '🇻🇺', maxLength: 7 },
  { code: 'VE', name: 'Venezuela', dial: '+58', flag: '🇻🇪', maxLength: 10 },
  { code: 'VN', name: 'Vietnam', dial: '+84', flag: '🇻🇳', maxLength: 9 },
  { code: 'WF', name: 'Wallis and Futuna', dial: '+681', flag: '🇼🇫', maxLength: 6 },
  { code: 'YE', name: 'Yemen', dial: '+967', flag: '🇾🇪', maxLength: 9 },
  { code: 'ZM', name: 'Zambia', dial: '+260', flag: '🇿🇲', maxLength: 9 },
  { code: 'ZW', name: 'Zimbabwe', dial: '+263', flag: '🇿🇼', maxLength: 9 },
];

